# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'enc.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import binascii
import os


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 400)
        Form.setMinimumSize(QtCore.QSize(400, 400))
        Form.setMaximumSize(QtCore.QSize(400, 400))
        self.input_TextEdit = QtWidgets.QTextEdit(Form)
        self.input_TextEdit.setGeometry(QtCore.QRect(20, 60, 271, 81))
        self.input_TextEdit.setObjectName("input_TextEdit")
        self.input_label = QtWidgets.QLabel(Form)
        self.input_label.setGeometry(QtCore.QRect(130, 40, 161, 20))
        self.input_label.setObjectName("input_label")
        self.type_ComboBox = QtWidgets.QComboBox(Form)
        self.type_ComboBox.setGeometry(QtCore.QRect(310, 70, 69, 22))
        self.type_ComboBox.setObjectName("type_ComboBox")
        self.method_ComboBox = QtWidgets.QComboBox(Form)
        self.method_ComboBox.setGeometry(QtCore.QRect(310, 110, 69, 22))
        self.method_ComboBox.setObjectName("method_ComboBox")
        self.ouput_TextBrowser = QtWidgets.QTextBrowser(Form)
        self.ouput_TextBrowser.setGeometry(QtCore.QRect(20, 220, 361, 161))
        self.ouput_TextBrowser.setObjectName("ouput_TextBrowser")
        self.output_label = QtWidgets.QLabel(Form)
        self.output_label.setGeometry(QtCore.QRect(310, 200, 61, 20))
        self.output_label.setObjectName("output_label")
        self.open_Button = QtWidgets.QPushButton(Form)
        self.open_Button.setGeometry(QtCore.QRect(20, 150, 75, 23))
        self.open_Button.setObjectName("open_Button")
        self.confirm_Button = QtWidgets.QPushButton(Form)
        self.confirm_Button.setGeometry(QtCore.QRect(210, 150, 75, 23))
        self.confirm_Button.setObjectName("confirm_Button")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Xtools_v1.0"))
        from icon import base64_img
        img = binascii.a2b_base64(base64_img)
        with open("tmp.jpg","wb") as f:
            f.write(img)
        Form.setWindowIcon(QtGui.QIcon("./tmp.jpg"))
        os.remove("./tmp.jpg")
        self.input_label.setText(_translate("Form", "输入文本/文件路径/拖动文件"))
        self.output_label.setText(_translate("Form", "无输入"))
        self.open_Button.setText(_translate("Form", "open"))
        self.confirm_Button.setText(_translate("Form", "confirm"))
